import Head from 'next/head'

import { signIn } from 'next-auth/react'

import Logo from 'components/Icons/Logo'

export default function Login () {
  return (
    <>
      <Head>
        <title>ChatGPT | OpenAI</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.svg' />
      </Head>

      <div className='bg-[#343541] h-screen flex flex-1 justify-center items-center flex-col'>
        <div className='w-96 flex flex-col justify-center items-center'>
          <div className='mb-5'>
            <Logo />
          </div>
          <div className='mb-2 text-center text-white'>Welcome to ChatGPT</div>
          <div className='mb-4 text-center text-white'>Log in with your OpenAI account to continue</div>
        </div>
        <div className='flex flex-row gap-3'>
          <button className='btn flex justify-center gap-2' onClick={() => signIn('google')}>
            Log in
          </button>
        </div>
      </div>
      <div className='absolute top-0 left-0 right-0 z-50' />
    </>
  )
}
