import Head from 'next/head'

import { getProviders, useSession, getSession } from 'next-auth/react'

export default function Home ({ providers }) {
  const { data: session } = useSession()

  if (!session) return <h1>Login</h1>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <h1>ChatGPT Messager</h1>
    </>
  )
}

export async function getServerSideProps (context) {
  const providers = await getProviders()
  const session = await getSession(context)

  return {
    props: {
      providers,
      session
    }
  }
}
