import Head from 'next/head'

import { getProviders, useSession, getSession } from 'next-auth/react'
import Login from 'components/Login'

export default function Home ({ providers }) {
  const { data: session } = useSession()

  if (!session) return <Login providers={providers} />
  return (
    <>
      <Head>
        <title>ChatGPT | OpenAI</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.svg' />
      </Head>

      <div className='flex'>
        {/* Sidebar */}
        {/* ClientProvider - Notification */}

        <div className='bg-[#343541] flex-1'>
          Inicio
        </div>
      </div>
    </>
  )
}

export async function getServerSideProps (context) {
  const providers = await getProviders()
  const session = await getSession(context)

  return {
    props: {
      providers,
      session
    }
  }
}
